api/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
    # Examples:
    url(r'^login_ad', views.login_ad, name='login_ad'),
    url(r'^login', views.login, name='login'),
    url(r'^auth', views.auth, name='auth'),
    url(r'^portal', views.portal, name='portal'),
    url(r'^ping', views.ping, name='ping'),


)

smartwifi/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'core.views.index', name='core.index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^core/', include('core.urls')),
    url(r'^management/', include('management.urls')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

api/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render, redirect, get_object_or_404, render_to_response, get_list_or_404
import json
from django.http import HttpResponse, HttpResponseRedirect, Http404
from datetime import datetime, date, time, timedelta
from management.models import Gateway, WifiClient, Ad, AdStat
from django.utils import timezone


def login(request):
    gw_address = request.GET.get('gw_address')
    gw_port = request.GET.get('gw_port')
    gw_id = request.GET.get('gw_id')
    mac = request.GET.get('mac')
    url = request.GET.get('url')

    if request.method == 'POST':
        mobile = request.POST.get('mobile')
        password = request.POST.get('password')
        print mobile, password
        if mobile and password is None:
            #TODO send SMS to get password
            pass
        elif mobile and password:
            #TODO verify password
            import uuid
            token = uuid.uuid1()
            print token
            gateway = get_object_or_404(Gateway, pk=gw_id)
            try:
                client = get_object_or_404(WifiClient, mac=mac)
            except Http404:
                client = WifiClient(phone=mobile, mac=mac)
            client.gateway = gateway
            client.token = token
            client.last_login = datetime.today()
            client.save()

            #save url in session
            request.session['url'] = url
            request.session['token'] = token

            redirect_url = 'http://{}:{}/wifidog/auth?token={}'.format(gw_address, gw_port, token)
            return HttpResponseRedirect(redirect_url)

    return render(request, 'api/login.html')


def auth(request):
    stage = request.GET.get('stage')
    ip = request.GET.get('ip')
    mac = request.GET.get('mac')
    token = request.GET.get('token')
    incoming = request.GET.get('incoming')
    outgoing = request.GET.get('outgoing')

    if mac and token:
        if token == request.session.get('token'):
            data = {'Auth': 1}
    else:
        data = {'Auth': 1}

    return HttpResponse(json.dumps(data), content_type="application/json")


def portal(request):
    #TODO
    url = request.session.get('url')
    print url
    if url:
        return HttpResponseRedirect(url)
    else:
        #redirect to ad3
        pass

    return HttpResponse('OK', content_type="application/json")


def ping(request):
    gw_id = request.GET.get('gw_id')
    sys_uptime = request.GET.get('sys_uptime')
    sys_memfree = request.GET.get('sys_memfree')
    sys_memtotal = request.GET.get('sys_memtotal')

    gateway = get_object_or_404(Gateway, id=gw_id)

    #TODO
    data = {'ssid': 'test ssid', 'authmode': 'open', 'password': '11111111', 'channel': 'test', 'pinginterval': 10}

    return HttpResponse(json.dumps(data), content_type="application/json")


def login_ad(request):
    images = []
    result = {}
    ads = Ad.objects.all()
    for ad in ads:
        if ad.ad_img:
            images.append(ad)

    if len(images) > 0:
        import random
        ad = images[random.randint(0, len(images)-1)]
        result['content'] = ad.ad_text
        result['image'] = ad.ad_img.url

        stat = AdStat(ad=ad, showtime=timezone.now())
        stat.save()

    return HttpResponse(json.dumps(result), content_type="application/json")

api/templates/api/login.html
<!DOCTYPE html>
{% load i18n staticfiles%}
<html class="bg-black">
    <head>
        <meta charset="UTF-8">
        <title>SmartWifi | Log in</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap-theme.min.css" %}">
        <link rel="stylesheet" href="{% static "fontawesome/css/font-awesome.min.css" %}">
        <!-- Theme style -->
        <link href="{% static 'css/AdminLTE.css' %}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="bg-black">

        <div class="form-box" id="login-box">
            <div class="header">Smart WIFI</div>
            <form method="post">{% csrf_token %}
                <div class="body bg-gray">
                    <div class="form-group">
                        <input type="text" name="mobile" class="form-control" placeholder="{% trans 'Mobile' %}"/>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn bg-olive btn-block">{% trans "Get Code" %}</button>
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" class="form-control" placeholder="{% trans 'Password' %}"/>
                    </div>
                </div>
                <div class="footer">
                    <button type="submit" class="btn bg-olive btn-block">{% trans "Log In" %}</button>
                </div>
            </form>

        </div>

        <div class="form-box" id="ad-box">
            <div class="body" id="content" hidden="hidden"></div>
        </div>

        <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
        <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
        <script>
            $(document).ready(function(){
                var url = "{% url 'management.ad.detail' pk=99999 %}";
                $.get("{% url 'api:login_ad' %}", function(data){
                    console.log(data);
                    var large_image = $('<img />');
                    large_image.attr('src', data.image);
                    if (data.content.length!=0){
                        $("#content").show();
                        $("#content").text(data.content);
                    }

                    $("#ad-box").append(large_image);
                });

            });
        </script>

    </body>
</html>