api/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
    # Examples:
    url(r'^login_ad', views.login_ad, name='login_ad'),
    url(r'^login', views.login, name='login'),
    url(r'^auth', views.auth, name='auth'),
    url(r'^portal', views.portal, name='portal'),
    url(r'^ping', views.ping, name='ping'),


)

core/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'worksmart.views.home', name='home'),
    #url(r'^$', views.trend, name='trend'),
    url(r'^dashboard/$', views.dashboard, name='core.dashboard'),
)

smartwifi/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'core.views.index', name='core.index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^core/', include('core.urls')),
    url(r'^management/', include('management.urls')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

accounts/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from management.validator import validate_phone


class BaseUser(models.Model):
    user = models.OneToOneField(User, blank=True, null=True)
    username = models.CharField(verbose_name=_('Username'), max_length=32)
    password = models.CharField(verbose_name=_('Password'), max_length=32)
    #full_name = models.CharField(verbose_name=_('Full Name'), max_length=32, blank=True, null=True)
    phone = models.CharField(verbose_name=_('Phone'), max_length=32, blank=True, null=True, validators=[validate_phone])
    qq = models.CharField(verbose_name=_('QQ'), max_length=32, blank=True, null=True)
    email = models.EmailField(verbose_name=_('Email'), max_length=32)
    override_ad1 = models.BooleanField(verbose_name=_('override_ad1'), default=False)
    ad1 = models.ForeignKey('management.Ad', verbose_name=_('ad1'), related_name='ad1', blank=True, null=True)
    override_ad2 = models.BooleanField(verbose_name=_('override_ad2'), default=False)
    ad2 = models.ForeignKey('management.Ad', verbose_name=_('ad2'), related_name='ad2', blank=True, null=True)
    override_ad3 = models.BooleanField(verbose_name=_('override_ad3'), default=False)
    ad3 = models.ForeignKey('management.Ad', verbose_name=_('ad3'), related_name='ad3', blank=True, null=True)
    override_ssid = models.BooleanField(verbose_name=_('override_ssid'), default=False)
    ssid = models.CharField(verbose_name=_('SSID'), max_length=64, blank=True, null=True)
    sms_template = models.CharField(verbose_name=_('SMS Template'), max_length=256, blank=True, null=True)
    comment = models.CharField(verbose_name=_('Comment'), max_length=512, blank=True, null=True)
    signup_flag = models.BooleanField(default=True)

    def __unicode__(self):
        return self.username


class SysAdmin(BaseUser):
    super_admin = models.BooleanField(verbose_name=_('Super Admin'), default=True)


class Agent(BaseUser):
    full_name = models.CharField(verbose_name=_('Full Name'), max_length=32, blank=True, null=True)


class Customer(BaseUser):
    full_name = models.CharField(verbose_name=_('Full Name'), max_length=32, blank=True, null=True)
    agent = models.ForeignKey(Agent, verbose_name=_('Agent'), blank=True, null=True)


# method for create user after create Agent
@receiver(post_save, sender=Agent)
def create_agent_user(sender, instance, **kwargs):
    print sender
    print '**' * 10
    print kwargs
    print instance
    print instance.username
    print instance.password
    if kwargs['created'] and instance.signup_flag:
        new_user = User.objects.create_user(instance.username, instance.email, instance.password)

        #add user to AgentGroup
        agent_group = Group.objects.get(name='AgentGroup')
        print agent_group
        new_user.groups.add(agent_group)
        new_user.save()

        agent = Agent.objects.get(username= instance.username)
        agent.user = new_user
        agent.save()


@receiver(post_save, sender=SysAdmin)
def create_admin_user(sender, instance, **kwargs):
    print sender
    print '**' * 10
    print kwargs
    print instance
    print instance.username
    print instance.password
    if kwargs['created']:
        new_user = User.objects.create_user(instance.username, instance.email, instance.password)

        #add user to AgentGroup
        if instance.super_admin:
            super_admin_group = Group.objects.get(name='SuperAdminGroup')
            new_user.groups.add(super_admin_group)
            new_user.save()
        else:
            admin_group = Group.objects.get(name='AdminGroup')
            new_user.groups.add(admin_group)
            new_user.save()

        sys_admin = SysAdmin.objects.get(username=instance.username)
        sys_admin.user = new_user
        sys_admin.save()


@receiver(post_save, sender=Customer)
def create_customer_user(sender, instance, **kwargs):
    print sender
    print '**' * 10
    print kwargs
    print instance
    print instance.username
    print instance.password
    if kwargs['created'] and instance.signup_flag:
        new_user = User.objects.create_user(instance.username, instance.email, instance.password)

        #add user to AgentGroup
        customer_group = Group.objects.get(name='CustomerGroup')
        print customer_group
        new_user.groups.add(customer_group)
        new_user.save()

        customer = Customer.objects.get(username=instance.username)
        customer.user = new_user
        customer.save()

@receiver(post_delete)
def delete_admin_user(sender, instance, **kwargs):
    print sender
    list_of_models = ('SysAdmin', 'Agent', 'Customer')
    if sender.__name__ in list_of_models:
        print '**' * 10
        print kwargs
        print instance
        print instance.username
        user = User.objects.get(username=instance)
        print user
        user.delete()

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from accounts.models import Agent, Customer
from management.models import Gateway, WifiClient


def index(request):
    return render(request, 'index.html')


# Create your views here.
def dashboard(request, template="dashboard.html"):
    agent_count = Agent.objects.count()
    customer_count = Customer.objects.count()
    gateway_count = Gateway.objects.count()
    client_count = WifiClient.objects.count()

    return render(request, template, {'agent_count': agent_count, 'customer_count': customer_count,
                                      'gateway_count': gateway_count, 'client_count': client_count})

core/templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load  i18n future staticfiles %}

<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
<meta name="description" content="{% block meta_description %}{% endblock %}">
<title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
<link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

<link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap-theme.min.css" %}">
{% block extra_css %}{% endblock %}

<script src="{% static "jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
{% block extra_js %}{% endblock %}

<!--[if lt IE 9]>
<script src="{% static "js/html5shiv.js" %}"></script>
<script src="{% static "js/respond.min.js" %}"></script>
<![endif]-->

{% block extra_head %}{% endblock %}
</head>

<body id="{% block body_id %}body{% endblock %}">
{% block content %}{% endblock %}
</body>
</html>

core/templates/core_base.html
{% extends "base.html" %}
{% load i18n staticfiles%}

{% block extra_css %}
<link rel="stylesheet" href="{% static "fontawesome/css/font-awesome.min.css" %}">
<style>
    footer{
        position: fixed;
        width: 100%;
        height:60px;
        background-color: #f5f5f5;
        bottom:0px;
        padding-top: 20px;
    }    
    #main {
        /* margin-bottom ensures that last
            content is not obscured by footer */
        margin-bottom: 69px;
    }
</style>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'vendor/favico-0.3.4.min.js' %}"></script>
    <script>
    $(document).ready(function() {
        var favicon = new Favico({
            animation : 'popFade'
        });

        $.get("{% url 'management.notification_data' %}",function(data){
           console.log("success.");
        }).done(function(data){
            var count = data.length;
            $("#badge").text(count);

            favicon.badge(count);
        });

{#        $('#plusOne').click(function() {#}
{#            badge = badge + 1;#}
{#            favicon.badge(badge);#}
{#        });#}
{#        $('#minusOne').click(function() {#}
{#            badge = (badge-1 < 0) ? 0 : (badge - 1);#}
{#            favicon.badge(badge);#}
{#        });#}
{#        $('#reset').click(function() {#}
{#            favicon.reset();#}
{#        });#}

    });
    </script>
{% endblock %}

{% block content %}
<div id="wrapper">
<header>
    {% block header %}
        <nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <a class="navbar-brand" href="{% url 'core.dashboard' %}"><b>{% trans "SmartWifi" %}</b></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            {% if perms.accounts.add_sysadmin %}
                <li class="active"><a href="{% url "accounts.sysadmins" %}">{% trans "System Admin" %}</a></li>
            {% endif %}
            {% if perms.accounts.add_agent %}
                <li><a href="{% url "accounts.agents" %}">{% trans "Agents"%}</a></li>
            {% endif %}
            {% if perms.accounts.add_customer %}
                <li><a href="{% url "accounts.customers" %}">{% trans "Customers"%}</a></li>
            {% endif %}
            <li><a href="{% url "management.gateways" %}">{% trans "Gateway Management"%}</a></li>
            <li><a href="{% url "management.clients" %}">{% trans "Client Stats"%}</a></li>
            <li><a href="{% url "management.ads" %}">{% trans "AD Management"%}</a></li>
            <li><a href="{% url "management.templates" %}">{% trans "Market Management"%}</a></li>
{#        <li><a href="#">{% trans "Selection" %}</a></li>#}
        </ul>
{#      <form class="navbar-form navbar-left" role="search">#}
{#        <div class="form-group">#}
{#          <input type="text" class="form-control" placeholder="Search">#}
{#        </div>#}
{#      </form>#}
      <ul class="nav navbar-nav navbar-right">
          <li>
              <a href="{% url 'management.notifications' %}">{% trans "Notification" %} <span class="badge" id="badge"></span></a>
          </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cog fa-2x"></i></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'profile' %}">{% trans "Settings" %}</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'logout' %}">{% trans "Sign Out" %}</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    {% endblock %}
</header>

    <div class="container">
    {% if messages %}
    <div class="messages">
    {% for message in messages %}
    <div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    </div>
    {% endif %}

    <h1>{% block title %}{% endblock %}</h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-2">
                {% block left_panel %}
                {% endblock %}
            </div>

            <div class="col-md-8" id="main">
                {% block main %}{% endblock %}
            </div>

{#            <div class="col-md-2">#}
{#                <div class="panel panel-default">#}
{#                    <div class="panel-body">#}
{#                    {% block right_panel %}#}
{#                    {% endblock %}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <p class="site-info text-center">
                    {% trans "Powered by" %}
                    <a href="http://getbootstrap.com">Bootstrap</a>
                    {% trans "and" %}
                    <a href="http://www.djangoproject.com">Django</a>
                </p>
            </div>
        </div>
    </footer>
</div>
{% endblock %}

core/templates/dashboard.html
{% extends "base_template.html" %}
{% load i18n staticfiles%}

{% block extra_js %}
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{#    <script src="{% static 'js/dashboard.js' %}" type="text/javascript"></script>#}
{% endblock %}

{% block content-header %}
<h1>
    {% trans "Home" %}
    <small>{% trans "System Summary" %}</small>
</h1>
{% endblock %}

{% block content%}
                    <!-- Small boxes (Stat box) -->
                    <div class="row">
                        <div class="col-lg-3 col-xs-6">
                            <!-- small box -->
                            <div class="small-box bg-aqua">
                                <div class="inner">
                                    <h3>
                                        {{ agent_count }}
                                    </h3>
                                    <p>
                                        {% trans "Agents" %}
                                    </p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-man"></i>
                                </div>
                                <a href="{% url 'accounts.agents' %}" class="small-box-footer">
                                    {% trans "More info" %} <i class="fa fa-arrow-circle-right"></i>
                                </a>
                            </div>
                        </div><!-- ./col -->
                        <div class="col-lg-3 col-xs-6">
                            <!-- small box -->
                            <div class="small-box bg-green">
                                <div class="inner">
                                    <h3>
                                        {{ customer_count }}
{#                                        <sup style="font-size: 20px">%</sup>#}
                                    </h3>
                                    <p>
                                        {% trans "Customers" %}
                                    </p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-person-add"></i>
                                </div>
                                <a href="{% url 'accounts.customers' %}" class="small-box-footer">
                                    {% trans "More info" %} <i class="fa fa-arrow-circle-right"></i>
                                </a>
                            </div>
                        </div><!-- ./col -->
                        <div class="col-lg-3 col-xs-6">
                            <!-- small box -->
                            <div class="small-box bg-yellow">
                                <div class="inner">
                                    <h3>
                                        {{ gateway_count }}
                                    </h3>
                                    <p>
                                        {% trans "Gateways" %}
                                    </p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-android-wifi"></i>
                                </div>
                                <a href="{% url 'management.gateways' %}" class="small-box-footer">
                                    {% trans "More info" %} <i class="fa fa-arrow-circle-right"></i>
                                </a>
                            </div>
                        </div><!-- ./col -->
                        <div class="col-lg-3 col-xs-6">
                            <!-- small box -->
                            <div class="small-box bg-red">
                                <div class="inner">
                                    <h3>
                                        {{ client_count }}
                                    </h3>
                                    <p>
                                        {% trans "Clients" %}
                                    </p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-ios7-people"></i>
                                </div>
                                <a href="{% url 'management.clients' %}" class="small-box-footer">
                                    {% trans "More info" %} <i class="fa fa-arrow-circle-right"></i>
                                </a>
                            </div>
                        </div><!-- ./col -->
                    </div><!-- /.row -->

                    <!-- Main row -->
                    <div class="row">
                        <!-- Left col -->
                        <section class="col-lg-7 connectedSortable">

                            <!-- Notification List -->
                            <div class="box box-primary">
                                <div class="box-header">
                                    <i class="fa fa-bell"></i>
                                    <h3 class="box-title">{% trans "Notifications" %}</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <ul class="todo-list">
                                    </ul>
                                </div><!-- /.box-body -->
                                <div class="box-footer clearfix no-border">
                                    <a href="{% url 'management.notifications' %}" class="btn btn-default pull-right">{% trans "View All" %}</a>
                                </div>
                            </div><!-- /.box -->


                            <!-- Custom tabs (Charts with tabs)-->
                            <div class="nav-tabs-custom">
                                <!-- Tabs within a box -->
                                <ul class="nav nav-tabs pull-right">
                                    <li class="active"><a href="#revenue-chart" data-toggle="tab">Area</a></li>
                                    <li><a href="#sales-chart" data-toggle="tab">Donut</a></li>
                                    <li class="pull-left header"><i class="fa fa-inbox"></i> {% trans "Gateways" %}</li>
                                </ul>
                                <div class="tab-content no-padding">
                                    <!-- Morris chart - Sales -->
                                    <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 300px;"></div>
                                    <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 300px;"></div>
                                </div>
                            </div><!-- /.nav-tabs-custom -->
                        </section><!-- /.Left col -->

                        <!-- right col (We are only adding the ID to make the widgets sortable)-->
                        <section class="col-lg-5 connectedSortable">
                            <div class="box box-solid bg-light-blue-gradient">
                                <div class="box-header">
                                    <i class="fa fa-area-chart"></i>
                                    <h3 class="box-title">{% trans "Customers Graph" %}</h3>
                                    <div class="box-tools pull-right">
                                        <button class="btn bg-teal btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                        <button class="btn bg-teal btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
                                    </div>
                                </div>
                                <div class="box-body border-radius-none">
                                    <div class="chart" id="line-chart" style="height: 250px;"></div>
                                </div><!-- /.box-body -->
{#                                <div class="box-footer no-border">#}
{#                                    <div class="row">#}
{#                                    </div><!-- /.row -->#}
{#                                </div><!-- /.box-footer -->#}
                            </div><!-- /.box -->

                            <!-- solid sales graph -->
                            <div class="box box-solid bg-teal-gradient">
                                <div class="box-header">
                                    <i class="fa fa-th"></i>
                                    <h3 class="box-title">{% trans "Clients Graph" %}</h3>
                                    <div class="box-tools pull-right">
                                        <button class="btn bg-teal btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                        <button class="btn bg-teal btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
                                    </div>
                                </div>
                                <div class="box-body border-radius-none">
                                    <div class="chart" id="line-chart" style="height: 250px;"></div>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->



                        </section><!-- right col -->
                    </div><!-- /.row (main row) -->

                </section><!-- /.content -->
{% endblock %}

core/templates/dashboard_backup.html
{% extends "core_base.html" %}
{% load i18n %}